---

- name: get rackcontrollers
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/rackcontrollers/"
    headers:
      Authorization: "{{ Authorization }}"
    return_content: true
  register: _rackcontrollers

#- debug:
#    var: _rackcontrollers.json

- name: provide dhcp on vlans
  when:
    - vlan.dhcp_on | default(false) != (_existing_vlans.json | json_query(comparison_vlan)).dhcp_on
  changed_when: true
  uri:
    url: "{{ maas_base }}/MAAS/api/2.0/fabrics/{{ fabric_id }}/vlans/{{ vlan.id }}/"
    method: PUT
    headers:
      Authorization: "{{ Authorization }}"
    body:
      primary_rack: "{{ _rackcontrollers.json | json_query(get_system_id) }}"
      dhcp_on: "{{ vlan.dhcp_on | default(false) }}"
#      vid: "{{ vlan.id }}"
    body_format: json
  loop: "{{ maas_network.fabrics[fabric] }}"
  loop_control:
    loop_var: vlan
  vars:
    # FIXME hardcoded hostname=='maas'
    get_system_id: "[?hostname=='maas'].system_id | [0]"
    comparison_vlan: "[?vid==`{{ vlan.id }}`] | [0]"
